### ISSUE TITLE
eventdrop in resourceday is modifying the day of the event

### ISSUE THREAD

**Issue by beinto** [seankenny/fullcalendar#10]
when we drag an recsource to another resource it is changing the day of the evetn as if it was in week view

**Comment by siegerhansma** [comment]
Have you managed to find a workaround or patch for this?

**Comment by seankenny** [comment]
Should be fixed with latest commit - https://github.com/seankenny/fullcalendar/commit/099351a0b5171497787b2f0f3659411fe1d9bc78
