### ISSUE TITLE
Destroy and Recreate Resource header when changing date

### ISSUE THREAD

**Issue by mattg8000** [seankenny/fullcalendar#12]
Hi Sean
We are considering using your fork of the FullCalendar for an upcoming project that requires a "resource" view for days.  The only issue which is holding us back is the following requirement:
The "resources" are members of staff who have a start and end date to their employment, when using the previous, next or date setting functions of the day view we will need to re-get and re-render the resource headers.
We considered amending the fetchAndRenderEvents function to call fetchResources, however the fetchResources function is not available (defined) at this scope.
We are also not sure of the sequence of calls to make to re-render the table header once new resources are retrieved.
We are quite willing to do the donkey work and give back if you can point us in the right direction, failing that would you consider completing the above change for a fee?
All the best
Matt

**Comment by seankenny** [comment]
Far too late to be of help but fixed by the PR 3f75a1db13a49f4ae0bf62906ee0c858ca9f24cc
