### ISSUE TITLE
Not able to get resource ID

### ISSUE THREAD

**Issue by jochem4207** [seankenny/fullcalendar#13]
When I drop a event in to the calendar. I expect to get some resource information.
The only info I seem to get is all resources when I call the view object.

See my SO question for lot more info:

http://stackoverflow.com/questions/22939239/fullcalendar-get-position-or-get-get-resource

This is fixed by the new update. super thanks! Can be closed!

**Comment by seankenny** [comment]
Check out https://github.com/seankenny/fullcalendar/blob/master/tests/droppable_resourceView.html for a demo on how to achieve this (following an update to the ResourceView.js code).
