### ISSUE TITLE
Resource id on select

### ISSUE THREAD

**Issue by loule** [seankenny/fullcalendar#15]
Just like the drop, would be nice to get the resource id when selecting time slots to create an event. To really use it like an agenda.

**Comment by seankenny** [comment]
Check out https://github.com/seankenny/fullcalendar/blob/master/tests/day_render.html for a demo on how to achieve this (following an update to the ResourceView.js code).

456678312898a74be845b181a4e1e9a9af2f7052

**Comment by loule** [comment]
Sorry but i've tried a lot of things but.... can't make it work. I can get resource with some dirty code, but if try anything like renderEvent or other... doesnt work..

**Comment by seankenny** [comment]
Did you try:  dayClick: function(date, allDay, ev, view) {
                console.log(date, allDay, ev);
            },

Check the ev.data property for the resource.
