### ISSUE TITLE
When adding event to another resource, date is pushed by 1 day

### ISSUE THREAD

**Issue by benkelukas** [seankenny/fullcalendar#16]
Hi, i don't know, if this is intended functionality, but when i select a field in another resource than the first one, the date that is returned from select callback is larger by one day. e.g.
I have two resources and date in calendar is 2014-07-02, when i select slots in resource no. 2, the date returned from select callback is 2014-07-03. Is there some workaround or configuration option that I could use? Thanks in advance.

**Comment by seankenny** [comment]
Not 100% sure if this fixes the issue you have but see - http://plnkr.co/edit/6zXwPX9cFkubhnHwHJIR?p=preview

Select either the event in the "Eco Office 2" column and check the console.log value output or click anywhere in the "Eco Office 2" col to see and check the console.log value output.  Just fixing an issue with the 2nd of these..

**Comment by seankenny** [comment]
Fixed with 76746eb250d5aef59932d4d062c86838609e3c83
