### ISSUE TITLE
v2 does not accept resourceDay view

### ISSUE THREAD

**Issue by zvictor** [seankenny/fullcalendar#20]
How do I start developing with the current `v2` branch? Is its API different than the master's one?

Using the `defaultView: 'resourceDay'` proposed on the [documentation](http://www.seankenny.me/blog/2013/08/14/fullcalendar-with-a-resource-day-view/) throws an exception in `fullcalendar.js:705:17`  since `resourceDay` is not present in `fcViews` (which only contains _month, basicWeek, basicDay, agendaWeek and agendaDay_)

It would be even nicer to have a `demos/resource-view.html` to run a test.

**Comment by seankenny** [comment]
Hi.

Change the branch to V2 - https://github.com/seankenny/fullcalendar/tree/v2

Use the fullcalendar.js and fullcalendar.css in the dist/ folder.

Did you look @ the demo in the plunkr as [suggested](http://www.seankenny.me/blog/2014/08/11/fullcalendar-with-a-resource-day-view-v2-0-2/)? That should contain all you need.  Just hit the 'edit' link to see the source html and js/css (these point back to the github dist files I just mentioned.

There is a demo test html page in the code base as well that I use for dev - https://github.com/seankenny/fullcalendar/blob/v2/tests/resourceDayView.html

It does not use the concatinated/minified final fullcalendar.js but rather the individual source javascript files making it a lot easier to debug your way around.

**Comment by zvictor** [comment]
Oh yeah! I made silly mistakes merging our codes in my machine and then I couldn't make it work. My fault.

Anyway, I am sending a pull request right now that adds a demo page, in case someone else gets lost again like I did =)
