### ISSUE TITLE
How to load and display events by ajax in resourceDay

### ISSUE THREAD

**Issue by dakiquang** [seankenny/fullcalendar#25]
My source code: 

```
        jQuery('#tennis-calendar').fullCalendar({
            lang: 'en',
            height: 550,
            header: {
                left: 'title',
                center: '',
                right: 'prev,next,today agendaWeek,agendaDay,resourceDay'
            },
            defaultView: 'resourceDay',
            aspectRatio: 3,
            selectable: true,
            selectHelper: true,
            theme: false,
            editable: false,
            axisFormat: 'HH:mm',
            timeFormat: {
                agenda: 'H:mm'
            },
            allDaySlot: false,
            minTime: '07:00:00',
            maxTime: '18:00:00',
            forceEventDuration: true,
            droppable: false,
            hiddenDays: [],
            slotDuration: '00:30:00',
            resources: [{"name":"Court #6","id":"res6"},{"name":"Court #7","id":"res7"}],
            events: {
                url: 'http://tennis.dev/tennis/getDatas?type=event&show=2',
                success: function(data) {
                    console.log(data);
                }
            }
        });
```

It means, events will be get by Ajax when change date or clicks next, previous ...

But it does not working when loading events by ajax. How can display it?

Thanks,

**Comment by seankenny** [comment]
Can you let me know what you mean by not working - is there an error in the console or something?

Can you provide the response from the events ajax request please?

You are using the js code from the master branch (i.e. v1.6.x and not v2.0) right?

Thanks!

**Comment by seankenny** [comment]
Just created another plunkr using an ajax request for the events [here](http://embed.plnkr.co/maiZ4GBTnYC3NeFPMSL8/).  Looks like it works OK.  Can you verify please?

Thanks!

**Comment by dakiquang** [comment]
Hi @seankenny,

I'm using the js code from v2 branch. It seems not working with version 2.x.x. Could you please check with version 2.x.x

**Comment by seankenny** [comment]
Still looks OK to me.  Can you look @ the demo again - updated to use v2.0.2.  You did include the moment.js library right?

Thanks!

**Comment by dakiquang** [comment]
Hi @seankenny ,

Thanks for your support. I found problem in structure of events when ajax loaded. 

It should be "resources" instead of "resourceId"

{
"id":5,
"title":"event",
"start":"2014-08-26T08:00:00",
"end":"2014-08-26T09:00:00",
"allDay":false,
"resources":"3" // old is resourceId
}
