### ISSUE TITLE
revertFunc() not reverting event to original resource column - V2.0

### ISSUE THREAD

**Issue by sbaddam8** [seankenny/fullcalendar#27]
Sean,
  Thanks for this work.
  I have noticed that if an event is dragged from one resource to another resource column then it is not reverting back to original resource column, on calling revertFunc() from eventDrop callback. Rather it is showing up in new column with the original start and end time.

Thanks,
Sudheer

**Comment by seankenny** [comment]
Thanks Sudheer for the headsup on this.  Working on this now - 4d489a41eaa85c63f219653ea1f25c40e28bd092.  Drag/drop revert looks good now.  Just need to clean up and get working for the resize.  Should be done shortly and I'll merge back into 2.0.2.

Sorry for the delay!

**Comment by seankenny** [comment]
Fixed with ea7458aae4f3d2cd903ae9fd86104444a26c0c0d

**Comment by sbaddam8** [comment]
Thank you very much.
