### ISSUE TITLE
can't change language

### ISSUE THREAD

**Issue by marcir** [seankenny/fullcalendar#29]
I need to change language of calendar. I load all language js.
When i use base version of fullcalendar it works perfectly but when i use this fork it don't.
i set language in option

 lang: 'it',

can anyone help me?

**Comment by seankenny** [comment]
Hi Marcir,

I'll get to this one shortly.  I can see the issue and have a fix.

Sean

**Comment by seankenny** [comment]
Fixed with 79ef1f0820e91c09a8a672fd233171bd498ff988.

See http://embed.plnkr.co/HiVAiGYQL0HPf8iEshlq/preview for demo.

**Comment by marcir** [comment]
thanks seankenny
