### ISSUE TITLE
date time format for events

### ISSUE THREAD

**Issue by marcir** [seankenny/fullcalendar#30]
hello, 
as documentation of the trunk using the following syntax to specify the properties of the start and end of an event 

"start": "2014-09-03T09: 00" 
"end": "2014-09-03T10: 00" 

This solution works with all views except with the view resourceDay 

the resource day only works if I use the syntax 

  new Date (y, m, d, 9, 0) 

events are retrieved using ajax / php 

There is no way to solve?

**Comment by seankenny** [comment]
Hi.

I am not entirely sure of your issue here.  The dates you have supplied above are invalid as they have a space beteen the hour and minute segments.

Please see this plunkr I've added to demo events being returned in the format you have provided (ISO8601) with the space removed and also with events arriving via a url.  Fork & edit the plunkr to try both ways.

http://embed.plnkr.co/0bzA3OEi4GBRooJ7uPQg/preview

If I have missed your point, can you please provide a plunkr example so I don't waste time tracking down a possible issue?

Many thanks,
Sean

**Comment by marcir** [comment]
hello Sean 
thanks for the quick response. Sorry for the delay but I was in my work. 

the space that you see depended on the copy paste. however clearing all the browser cache seems to work properly. 

sorry for the inconvenience and thanks for your support

**Comment by marcir** [comment]
there was another problem. When specifying the value of the resources should not be placed between double quote 

"resource": "[1]" is wrong 

"resource": "[1] is corrected...

**Comment by seankenny** [comment]
Hi @marcir ,

Can you please elaborate?  You mean the "resources" property on the "events" array?  If so, this is as expected I think.  "resources" can be an array of ids, each id being a string so this is the valid way:

"resources": ["resourceid1", "resourceid2"]

Update me with more details if I have it wrong please.

Thanks,
Sean

**Comment by marcir** [comment]
hi seankenny ,
yes i refer property of events. excuse for superficiality. I thought it was clear.

**Comment by seankenny** [comment]
OK - so can you explain the issue please?  It appears to be working as I
would expect it to.

Thanks,
Sean

**Comment by marcir** [comment]
The problem as described in my first was to hide the events under resources. In the copy paste had happened that there was a space in the properties of the start and end of the event. The problem was not so much but the fact that, by generating events using php and json_encode, the property resource was inserted in the middle of the double quote. In order to work you have to remove the double quote. Since we do not know it did not work. I posted the experience to help any others who have the same problem. So everything works!
