### ISSUE TITLE
new work on resourceView-2.1

### ISSUE THREAD

**Issue by zvictor** [seankenny/fullcalendar#32]
Hi @seankenny !

I have seen around (#28) that you won't be able to update it to v2.1.x soon and I am really needing it asap.
So, I started doing it by myself = )

I forked the arshaw's v2.1.1, diffed from your implementation and added part of your code there. The result can be seen at [kirkeweb/fullcalendar#resourceView-2.1](https://github.com/KirkeWeb/fullcalendar/tree/resourceView-2.1).

With a few lines of code changes, due to the new OOP structure, I have been able to have a quite functional and stable result. There are still some issues, specially when the user start clicking and dragging around, but we already have something presentable (check the demo at `demos / resource-views.html`)

Now I am starting to test it, and I am inviting you and the community here to consider merging our efforts to continue to work from that branch.

Let me know your thoughts on that.

**Comment by seankenny** [comment]
Hi @zvictor,

Looks good - very similar to the approach I took.  I have been working on this over the last few days also.  Still a little rough but the drag/drop, etc are all working - I just need to take a look at simplifying a little befoer I release as beta.

See - https://github.com/seankenny/fullcalendar/tree/vnext.  It would be good to get a resolution for #28 as well as a possible implementation of gantt style resources.

**Comment by zvictor** [comment]
Cool! Now we have more options on the table.

Are you planning to fully test your branch?

**Comment by seankenny** [comment]
Yep.  You can see the Travis yaml in place - already running for the V2
branch.  I'll be adding more test coverage for resources as soon as I get a
chance.

**Comment by zvictor** [comment]
Nice, I could find some errors on my code just comparing with yours = D

Just to clarify, we still don't have any tests for resource view yet, right?

**Comment by seankenny** [comment]
Yep - and 3 or 4 of the existing tests are failing with ajax timeout exceed
exceptions also.  Was plainning on getting to these failures today/tomorrow.

The code in there now seems to handle drag/drop, language changes, undo,
etc, etc.  I couldn't find any regressions from v2.0.  There were a LOT of
changes though!

**Comment by seankenny** [comment]
BTW - I updated the master branch last night with the v2.1.1 codebase.
 I'll be dumping the vnext branch at some stage soon.
