### ISSUE TITLE
label of resourceDay button when simple day button is showed

### ISSUE THREAD

**Issue by marcir** [seankenny/fullcalendar#33]
Hallo,
i need to show either button day and resourceDay button
i  proved to change label in this way

 buttonText: {
                prev: '<<',
                next: '>>',
                prevYear: '&nbsp;&lt;&lt;&nbsp;',
                nextYear: '&nbsp;&gt;&gt;&nbsp;',
                today: 'oggi',
                month: 'mese',
                week: 'settimana',
                day: 'giorno2',
                resoureDay: 'risorsa'
            },

but the label of resourceDay button is giorno2.

thanks

**Comment by seankenny** [comment]
Hi - really sorry for the delay!  Not much time at the moment.

So it looks like you have a typo - you have "resoureDay" when it should be "resourceDay" (missing "c").

That should fix it.
