### ISSUE TITLE
Resource Day day click incrementing date v2.0

### ISSUE THREAD

**Issue by lunarlogicsolutions** [seankenny/fullcalendar#34]
When you click on the 1st resource column in a day slot, you get the day date return that you are on.  But when you click other columns, you get an incremented date (like you would get in agendaWeek view).  I changed line 6444 in the fullcalendar.js file to 'var date = cellToDate(0, 0);', so it would give me the same day for each resource column.  It is the 3rd line in the slotClick(ev) function.  You might have a better solution/fix, but just thought you would want to know that one.  Great work :)

**Comment by seankenny** [comment]
Thanks for the spot!  Fixed in e4dd8d37ee6db46e97f467bd5c6d5f2a5dab4dc0.

**Comment by martijn80** [comment]
Wow, ran into this one as well. Thanx for the fix!
