### ISSUE TITLE
Multiple Resource drag and drop support issue v2.0

### ISSUE THREAD

**Issue by lunarlogicsolutions** [seankenny/fullcalendar#36]
When you have an event with 3 resources assigned to it and drag one of them to a new resource, it removes the other 2.  I wrote a fix to replace the original value with the new value in the array instead.

In the element draggable stop event (line 7544 for me)

I replaced this:

resources = [getResources()[origCell.col + resourceDelta].id];

With:

var newid = getResources()[origCell.col + resourceDelta].id;

```
                        if ($.inArray(newid, resources) == -1) {
                            for (var i = 0; i < resources.length; i++) {
                                if (getResources()[origCell.col].id == resources[i])
                                    resources[i] = newid;
                            }
                        }
```

**Comment by seankenny** [comment]
Thanks for the sample.  The only issue is that if we are moving from r3 to r1 and r1 already exists, then we should probably retain only r1.  Changing to the following does the trick:

``` javascript
// given we have r1/r3 
// if we move r3 to r2, then we want to maintain r1/r2.
// if we move r3 to r1, then we only want to maintain r1 - so we splice the array
var resources = getResources();
var newId = resources[origCell.col + resourceDelta].id;
var oldId = resources[origCell.col].id;

var oldIndex = event.resources.indexOf(oldId);
var newIndex = event.resources.indexOf(newId);
if (newIndex > -1){
  event.resources = event.resources.splice(newIndex, 1);
} else {
  event.resources[oldIndex] = newId;
}
```

Work for you?

**Comment by lunarlogicsolutions** [comment]
You are on the right track and your approach is better than mine, but you have a couple of mistakes there.  Use the following, tested and works perfectly.

var resources = event.resources;
                        if (resourceDelta) {
                            var newId = getResources()[origCell.col + resourceDelta].id;
                            var oldId = getResources()[origCell.col].id;

```
                        var oldIndex = resources.indexOf(oldId);
                        var newIndex = resources.indexOf(newId);

                        if (newIndex > -1)
                            resources.splice(oldIndex, 1);
                        else
                            resources[oldIndex] = newId;
                    }
```
- Note just tested the All day section dragging around and it has the same original problem, it must have the same code in another section, will take a look.
