### ISSUE TITLE
revertFunc() not reverting event to original resource column #27

### ISSUE THREAD

**Issue by bulutcy** [seankenny/fullcalendar#40]
Hello,
This is the same issue with #27 .
As of today, revertFunc seems not working when we drag to different resource.

Tried to dive into source but was not able to make it works.
Any help is appreciated,
Regards.

**Comment by seankenny** [comment]
Caused by 7f478eb1b2a28a658b90a351a1805fd435a6ccf3

**Comment by seankenny** [comment]
Can you check this resolves the issue please?  If so, I'll close this out.

**Comment by bulutcy** [comment]
It is working well. Thank you.
