### ISSUE TITLE
Dragging/Resizing not working

### ISSUE THREAD

**Issue by victor-sopot** [seankenny/fullcalendar#57]
Great extension to an already fantastic jquery plugin man just what i needed for my project! 

I seem to be having a javascript error though, i am grabbing event and resource data with an Ajax pull as well as updating whenever an event is resized or moved. But events do not move at all and in console i am given this: 

Uncaught TypeError: eventElement.draggable is not a function - fullcalendar.js:7469

I've tried removing the eventDrop option completely.. at first i didn't have jquery-ui linked but then I enabled it and still nothing.. bit confused to be honest. Any ideas? If code snippets are required please let me know

**Comment by victor-sopot** [comment]
I updated to 2.1.1 from the master branch and i get a different error now when i click anywhere on the calendar: 

Uncaught TypeError: Cannot read property 'indexOf' of undefined

Also, under the Network tab of dev tools the ajax call to bring in resources seems to be looping like 15 times, any idea why this is happening?

**Comment by iRoachie** [comment]
+1

**Comment by HriBB** [comment]
+1

**Comment by HriBB** [comment]
I think that the problem is jquery-ui. It triggers a resize event on the calendar event div, which bubbles up all the way to window object, so when we do something like `$(window).resize()` it fires when we do resize.

Easy fix is

```
$(window).resize(function(e){
    if (e.target === window) {
        $('#calendar').fullCalendar('option', 'height', getCalendarHeight());
    }
});
```
