### ISSUE TITLE
refresh resources

### ISSUE THREAD

**Issue by beinto** [seankenny/fullcalendar#9]
how can i refresh the resources from the view?
Thanks

**Comment by seankenny** [comment]
You need to check the fullcalendar documentation:

http://arshaw.com/fullcalendar/docs/event_data/refetchEvents/

OR

http://arshaw.com/fullcalendar/docs/event_rendering/rerenderEvents/

Sean

**Comment by beinto** [comment]
I tried that but if I am in resourceDay view it does not render the view again . i tried to look in your code but do not find a way to do that....

**Comment by beinto** [comment]
Can you tell me in what function are the resources associated to the events? i can only associate once, when the calendar loads.

**Comment by seankenny** [comment]
Finally got to this - sorry for the delay.  See plunkr - http://plnkr.co/edit/cicfbVOpgVVxZmFOmCXK?p=preview.

Fixed with 1732e05f386bfb1868c0dc3cf31401cad6fa08c7
